### ISSUE TITLE
Permissions of groups reading in /etc/group line order

### ISSUE THREAD

**Issue by Cuttlerat** [millert/sudo#1]
If I set 
```
...
%admin ALL=(ALL) NOPASSWD:ALL
%sudo ALL=(ALL) ALL
...
```
in my `/etc/sudoers`
and in my `/etc/group`
```
...
sudo:x:1001:user
admin:x:1002:user
...
```
and if I try to run something with `sudo`, I will must to enter a password, because the sudo group higher in an order than admin group in `/etc/group`, however the admin group have a wider permissions than a sudo group have in a /etc/sudoers

Why the `sudo` read permissions of groups in order of lines in `/etc/group` before the first occuarance?
Why it does not use a most wide permission in `/etc/sudoers`?

**Comment by millert** [comment]
This is because in sudoers the last match takes precedence.
It has nothing to do with the /etc/group file order, only
the order of entries in /etc/sudoers matters.

 - todd

**Comment by Cuttlerat** [comment]
Thank you for your answer. I completely forgot about this. But why does the `sudo` take only the last match?
